# Generated by Django 6.0.4 on 2026-04-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='lst_name',
            new_name='last_name',
        ),
    ]
